TC-11
L4B0MB4/Teacrypt pull request #12
Opened 2020-09-04 15:25 UTC by L4B0MB4

2020-09-06 14:46 UTC, CrVnsh requested changes

2020-09-06 14:46 UTC, CrVnsh commented on backend/main.ts
> +console.log(key.exportKey("public"));
log

2020-09-06 14:46 UTC, CrVnsh commented on backend/main.ts
> +console.log("encrypted: ", encrypted);
log

2020-09-06 14:46 UTC, CrVnsh commented on backend/main.ts
> +console.log("decrypted: ", decrypted);
log

2020-09-07 15:35 UTC, L4B0MB4 commented on package.json
> +    "start-be": "webpack --config webpack.be.config.js --watch --mode development"
this will obviously change as soon as we have the monorepo

2020-09-07 15:36 UTC, L4B0MB4 commented on package.json
> +    "node-rsa": "^1.1.1"
locked it up and its frontend compatible as well if you use webpack 👍

2020-09-09 17:22 UTC, closed without merging